/**
 * This file holds the configuration "recipes" for each exercise
 * the app knows how to track. Makes adding new exercises easier.
 */
import type { ExerciseName, ExerciseRecipe } from '../types/poseTypes';

// Mapping of readable names to MediaPipe landmark indices
// Keep this for easy lookup within recipes
export const POSE_LANDMARKS = {
  NOSE: 0, LEFT_EYE_INNER: 1, LEFT_EYE: 2, LEFT_EYE_OUTER: 3, RIGHT_EYE_INNER: 4, RIGHT_EYE: 5, RIGHT_EYE_OUTER: 6, LEFT_EAR: 7, RIGHT_EAR: 8, MOUTH_LEFT: 9, MOUTH_RIGHT: 10,
  LEFT_SHOULDER: 11, RIGHT_SHOULDER: 12, LEFT_ELBOW: 13, RIGHT_ELBOW: 14, LEFT_WRIST: 15, RIGHT_WRIST: 16, LEFT_PINKY: 17, RIGHT_PINKY: 18, LEFT_INDEX: 19, RIGHT_INDEX: 20, LEFT_THUMB: 21, RIGHT_THUMB: 22,
  LEFT_HIP: 23, RIGHT_HIP: 24, LEFT_KNEE: 25, RIGHT_KNEE: 26, LEFT_ANKLE: 27, RIGHT_ANKLE: 28, LEFT_HEEL: 29, RIGHT_HEEL: 30, LEFT_FOOT_INDEX: 31, RIGHT_FOOT_INDEX: 32,
};

// Define the "recipe" for each known exercise
export const EXERCISE_RECIPES: { [key in Exclude<ExerciseName, 'none'>]: ExerciseRecipe } = {
  "squat": {
    displayName: "Squat",
    keyJoints: ["LEFT_HIP", "LEFT_KNEE", "LEFT_ANKLE", "RIGHT_HIP", "RIGHT_KNEE", "RIGHT_ANKLE"],
    primaryAngleJoints: ["RIGHT_HIP", "RIGHT_KNEE", "RIGHT_ANKLE"],
    secondaryAngleJoints: ["LEFT_HIP", "LEFT_KNEE", "LEFT_ANKLE"],
    defaultUp: 160, defaultDown: 110, upIsLarger: true,
  },
  "push-up": {
    displayName: "Push-up",
    keyJoints: ["RIGHT_SHOULDER", "RIGHT_ELBOW", "RIGHT_WRIST"], // Assuming right side dominant for now
    primaryAngleJoints: ["RIGHT_SHOULDER", "RIGHT_ELBOW", "RIGHT_WRIST"],
    // Could add left side as secondary if needed later
    defaultUp: 160, defaultDown: 100, upIsLarger: true,
  },
  "sit-up": {
    displayName: "Sit-up",
    keyJoints: ["RIGHT_SHOULDER", "RIGHT_HIP", "RIGHT_KNEE"], // Assuming right side dominant
    primaryAngleJoints: ["RIGHT_SHOULDER", "RIGHT_HIP", "RIGHT_KNEE"],
    defaultUp: 80, defaultDown: 160, upIsLarger: false, // UP angle is SMALLER for sit-ups
  }
  // --- Add new exercises here ---
  // "bicep-curl": { ... }
};

// General constants
export const VISIBILITY_THRESHOLD = 0.5;
export const HYSTERESIS_MARGIN = 5; // Degrees buffer
export const CALIBRATION_DELAY_MS = 3000; // 3 seconds

// Connection lines for drawing the pose skeleton (used in CameraView)
export const POSE_CONNECTIONS = [
  [POSE_LANDMARKS.NOSE, POSE_LANDMARKS.LEFT_EYE_INNER], [POSE_LANDMARKS.LEFT_EYE_INNER, POSE_LANDMARKS.LEFT_EYE], [POSE_LANDMARKS.LEFT_EYE, POSE_LANDMARKS.LEFT_EYE_OUTER], [POSE_LANDMARKS.LEFT_EYE_OUTER, POSE_LANDMARKS.LEFT_EAR],
  [POSE_LANDMARKS.NOSE, POSE_LANDMARKS.RIGHT_EYE_INNER], [POSE_LANDMARKS.RIGHT_EYE_INNER, POSE_LANDMARKS.RIGHT_EYE], [POSE_LANDMARKS.RIGHT_EYE, POSE_LANDMARKS.RIGHT_EYE_OUTER], [POSE_LANDMARKS.RIGHT_EYE_OUTER, POSE_LANDMARKS.RIGHT_EAR],
  [POSE_LANDMARKS.MOUTH_LEFT, POSE_LANDMARKS.MOUTH_RIGHT],
  [POSE_LANDMARKS.LEFT_SHOULDER, POSE_LANDMARKS.RIGHT_SHOULDER], [POSE_LANDMARKS.LEFT_SHOULDER, POSE_LANDMARKS.LEFT_ELBOW], [POSE_LANDMARKS.LEFT_ELBOW, POSE_LANDMARKS.LEFT_WRIST],
  [POSE_LANDMARKS.LEFT_WRIST, POSE_LANDMARKS.LEFT_PINKY], [POSE_LANDMARKS.LEFT_WRIST, POSE_LANDMARKS.LEFT_INDEX], [POSE_LANDMARKS.LEFT_WRIST, POSE_LANDMARKS.LEFT_THUMB], [POSE_LANDMARKS.LEFT_PINKY, POSE_LANDMARKS.LEFT_INDEX], // Palm
  [POSE_LANDMARKS.RIGHT_SHOULDER, POSE_LANDMARKS.RIGHT_ELBOW], [POSE_LANDMARKS.RIGHT_ELBOW, POSE_LANDMARKS.RIGHT_WRIST],
  [POSE_LANDMARKS.RIGHT_WRIST, POSE_LANDMARKS.RIGHT_PINKY], [POSE_LANDMARKS.RIGHT_WRIST, POSE_LANDMARKS.RIGHT_INDEX], [POSE_LANDMARKS.RIGHT_WRIST, POSE_LANDMARKS.RIGHT_THUMB], [POSE_LANDMARKS.RIGHT_PINKY, POSE_LANDMARKS.RIGHT_INDEX], // Palm
  [POSE_LANDMARKS.LEFT_SHOULDER, POSE_LANDMARKS.LEFT_HIP], [POSE_LANDMARKS.RIGHT_SHOULDER, POSE_LANDMARKS.RIGHT_HIP], [POSE_LANDMARKS.LEFT_HIP, POSE_LANDMARKS.RIGHT_HIP],
  [POSE_LANDMARKS.LEFT_HIP, POSE_LANDMARKS.LEFT_KNEE], [POSE_LANDMARKS.LEFT_KNEE, POSE_LANDMARKS.LEFT_ANKLE], [POSE_LANDMARKS.LEFT_ANKLE, POSE_LANDMARKS.LEFT_HEEL], [POSE_LANDMARKS.LEFT_HEEL, POSE_LANDMARKS.LEFT_FOOT_INDEX], [POSE_LANDMARKS.LEFT_ANKLE, POSE_LANDMARKS.LEFT_FOOT_INDEX],
  [POSE_LANDMARKS.RIGHT_HIP, POSE_LANDMARKS.RIGHT_KNEE], [POSE_LANDMARKS.RIGHT_KNEE, POSE_LANDMARKS.RIGHT_ANKLE], [POSE_LANDMARKS.RIGHT_ANKLE, POSE_LANDMARKS.RIGHT_HEEL], [POSE_LANDMARKS.RIGHT_HEEL, POSE_LANDMARKS.RIGHT_FOOT_INDEX], [POSE_LANDMARKS.RIGHT_ANKLE, POSE_LANDMARKS.RIGHT_FOOT_INDEX],
];
